---
# Install and setup PostgreSQL Streaming Replication
- hosts: localhost
  tasks:
  - name: Import variables for bootstrap playbook
    include_vars: './defaults/main.yml'

  - name: bootstrap
    include: 'tasks/bootstrap.yml'

- hosts: pgsql
  tasks:
  - name: Import variables for install playbook
    include_vars: './defaults/main.yml'

  - name: Base setup
    include: 'tasks/install.yml'

- hosts: pgmaster
  tasks:
  - name: import variables to setup master
    include_vars: './defaults/main.yml'

  - name: setup master  
    include: 'tasks/configure-master.yml'
    include: 'tasks/users.yml'
    include: 'tasks/databases.yml'

- hosts: pgslaves
  tasks:
  - name: import variables to setup slaves
    include_vars: './defaults/main.yml'
 
  - name: setup slaves
    include: 'tasks/configure-slaves.yml'

- hosts: pgsql
  tasks:
  - name: import variables to setup the flask app
    include_vars: './defaults/main.yml'

  - name: setup test flask app
    include: 'tasks/flask.yml'
    when: deploy_flask_testapp

