---
# Install and setup PostgreSQL Streaming Replication
- hosts: localhost
  tasks:
  - name: Import variables for bootstrap playbook
    include_vars: './defaults/main.yml'

  - name: bootstrap
    include: 'tasks/bootstrap.yml'

- hosts: pgsql
  tasks:
  - name: Import variables for install playbook
    include_vars: './defaults/main.yml'

  - name: Base setup
    include: 'tasks/install.yml'

- name: setup master
  hosts: pgmaster
  vars_files:
    - 'defaults/main.yml'
  tasks:
  - include: 'tasks/configure-master.yml'
  - include: 'tasks/users.yml'
  - include: 'tasks/databases.yml'

- name: setup slaves
  hosts: pgslaves
  vars_files:
    - 'defaults/main.yml'
  tasks:
  - include: 'tasks/configure-slaves.yml'

- name: setup test flask app
  hosts: pgsql
  vars_files:
    - 'defaults/main.yml'
  tasks:
  - include: 'tasks/flask.yml'
    when: deploy_flask_testapp

