# file: tasks/users.yml -- manage postgresql roles

- name: "Setup users: add postgresql roles"
  postgresql_user:
    state: present
    name: "{{ item.name }}"
    encrypted: no
    password: "{{ item.pass }}"
    role_attr_flags: "{{ item.flags }}"
  with_items: postgresql_users
  when: postgresql_users|length > 0

- name: "Setup users: add postgresql replication roles"
  postgresql_user:
    state: present
    name: "{{ postgresql_streaming_user.name }}"
    encrypted: no
    password: "{{ postgresql_streaming_user.pass }}"
    role_attr_flags: REPLICATION
  when: postgresql_streaming_user|length > 0
